apiVersion: v1
kind: Pod
metadata:
  name: emailer-client
  namespace: default
  labels:
    build: borg-05092033
spec:
  containers:
  - image: localhost:5000/emailer:borg-05092033
    command: ["node", "emailer-client.js"]
    imagePullPolicy: IfNotPresent
    name: emailer-client
