apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: emailer
spec:
  replicas: 1
  template:
    metadata:
      name: emailer
      labels:
        run: emailer
        build: borg-05092033
    spec:
      containers:
      - name: emailer
        image: localhost:5000/emailer:borg-05092033
        ports:
        - containerPort: 50051
        command: ["node", "emailer.js"]
---
apiVersion: v1
kind: Service
metadata:
  name: emailer-svc
  labels:
    run: emailer
spec:
  ports:
    # the port that this service should serve on
  - port: 50051
    targetPort: 50051
  selector:
    run: emailer
