apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: Heapster
  name: heapster
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30002
    targetPort: 8082
  selector:
    k8s-app: heapster
