apiVersion: v1
kind: Pod
metadata:
  name: route-guide-client
  namespace: default
  labels:
    build: borg-05091444
spec:
  containers:
  - image: localhost:5000/route_guide:borg-05091444
    command: ["node", "route_guide_client.js", "--db_path=route_guide_db.json"]
    imagePullPolicy: IfNotPresent
    name: route-guide-client
