apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: route-guide-client
spec:
  replicas: 1
  template:
    metadata:
      name: route-guide-client
      labels:
        build: borg-05071641
    spec:
      containers:
      - name: route-guide
        image: localhost:5000/route_guide:borg-05071641
        command: ["node", "route_guide_client.js", "--db_path=route_guide_db.json", "--server=ROUTE_GUIDE_SVC"]

