apiVersion: v1
kind: Service
metadata:
  labels:
    name: ledis
    role: service
  name: ledis
  namespace: default
spec:
  ports:
    - port: 6380
      targetPort: 6380
      name: tcp
    - port: 80
      targetPort: 11181
      name: http
  selector:
    name: ledisdb

