apiVersion: v1
kind: Pod
metadata:
  name: ledisdb
  labels:
    name: ledisdb
spec:
  volumes:
    - name: "storage"
      hostPath:
        path: "~/cluster_data/ledis_data"
  containers:
  - image: borg286/ledis
    ports:
    - containerPort: 6380
    - containerPort: 11181
    imagePullPolicy: IfNotPresent
    name: ledis-server
    volumeMounts:
      - mountPath: "/tmp/ledis-server"
        name: "storage"
  restartPolicy: Always
